name: Build and Publish Docker Image on Release

on:
  release:
    types: [published]  # Ejecuta este workflow cuando se publica una nueva release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/grupo2diplomado:${{ github.event.release.tag_name }}

      - name: Update Version in Helm
        run: |
            git clone https://github.com/ju4nr3v0l/grupo2diplomadok8s.git
            cd grupo2diplomadok8s/grupo2diplomado-chart
            sed -i "s/tag: .*/tag: ${{ github.event.release.tag_name }}/" values.yaml
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"

      - name: Commit and Push Changes
        uses: actions-js/push@master
        with:
          directory: grupo2diplomadok8s
          github_token: ${{ secrets.TOKEN }}
          repository: ju4nr3v0l/grupo2diplomadok8s
          message: Version updated ${date}